FROM nginx:alpine

RUN apk add --no-cache nginx-mod-rtmp

RUN mkdir -p /tmp/hls && chmod 777 /tmp/hls

COPY nginx.conf /etc/nginx/nginx.conf
COPY web/ /usr/share/nginx/html/

EXPOSE 1935 8080

CMD ["nginx", "-g", "daemon off;"]
